# This is the neoforge.mods.toml file for the Colorist mod.
# Documentation: https://docs.neoforged.net/docs/1.21.1/gettingstarted/modfiles/

modLoader = "kotlinforforge"
loaderVersion = "${kotlinforforge_version_range}"
license = "${mod_license}"
issueTrackerURL = "https://github.com/1026073226/colorist/issues"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "${mod_authors}"
description = '''
${mod_description}
'''
logoFile = "icon.png"

[[dependencies.${mod_id}]]
    modId = "neoforge"
    type = "required"
    versionRange = "${neo_version_range}"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.${mod_id}]]
    modId = "minecraft"
    type = "required"
    versionRange = "${minecraft_version_range}"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.${mod_id}]]
    modId = "kotlinforforge"
    type = "required"
    versionRange = "${kotlinforforge_version_range}"
    ordering = "NONE"
    side = "BOTH"
